name: Install the deps, build and run the tests
description: Install Graphviz and restore the NPM dependencies. Build the project, run tests and create the NPM package.

runs:
  using: composite
  steps:
    - name: Install Graphviz
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y graphviz

    - name: Install the dependencies
      shell: bash
      run: npm ci

    - name: Build stage
      shell: bash
      run: npm run build

    - name: Test stage
      shell: bash
      run: npm test

    - name: Pack the npm package
      shell: bash
      run: npm pack
