name: Install the deps, build and run the tests
description: Install Graphviz, install the NPM dependencies, run build and run tests

runs:
  using: composite
  steps:
    - name: Install Graphviz
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y graphviz

    - name: Install the dependencies
      shell: bash
      run: npm ci

    - name: Build stage
      shell: bash
      run: npm run build

    - name: Test stage
      shell: bash
      run: npm test
