name: CI (develop branch) on PR

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  baserun:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Restore the dependencies, build, run the tests and create the NPM package
        uses: ./.github/actions/base-preparation
